[api]
api_url="https://virtserver.swaggerhub.com/wcd_de_lab/top10/1.0.0/add"

[s3]
bucket='samialfifi'
folder='input'

[db]
user='admin'
database='superstore'
port=3306
host='database-2.cpoqmy6e2sw9.eu-north-1.rds.amazonaws.com'
schema='schema'

[run]
py_script="run.py"




    

    
