[api]
api_url="https://virtserver.swaggerhub.com/wcd_de_lab/top10/1.0.0/add"

[s3]
bucket='samialfifi'
folder='input'

[db]
user=''
database='superstore'
port=3306
host='.amazonaws.com'
schema='schema'

[run]
py_script="run.py"




    

    
